### ISSUE TITLE
Unable to execute HTTP request: Illegal length for VALUE_STRING: 2473448655032511812

### ISSUE THREAD

**Issue by pitarch** [pitarch/openrtb-kinesis#1]
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal length for VALUE_STRING: 2473448655032511812
 at [Source: (software.amazon.awssdk.core.io.ReleasableInputStream); line: -1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.dataformat.cbor.CBORParser._decodeExplicitLength(CBORParser.java:2773)
	at com.fasterxml.jackson.dataformat.cbor.CBORParser._finishTextToken(CBORParser.java:1947)
	at com.fasterxml.jackson.dataformat.cbor.CBORParser.getText(CBORParser.java:1334)
	at software.amazon.awssdk.protocols.json.internal.dom.JsonDomParser.parseToken(JsonDomParser.java:53)
	at software.amazon.awssdk.protocols.json.internal.dom.JsonDomParser.parse(JsonDomParser.java:41)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:167)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:79)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$5(BaseClientHandler.java:231)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)

```

**Comment by pitarch** [comment]
you must disable the cbor protocol
